export const Phase = {
  WORLD_SETTING: 'WORLD_SETTING',
  CHARACTER_SETTING: 'CHARACTER_SETTING',
  KEY_CHARACTER_SETTING: 'KEY_CHARACTER_SETTING',
  STORY_PLAY: 'STORY_PLAY',
};

export const SubState = {
  AWAITING_INPUT: 'AWAITING_INPUT',
  LLM_STREAMING: 'LLM_STREAMING',
  DICE_PENDING: 'DICE_PENDING',
  SUMMARIZING: 'SUMMARIZING',
};

export const FlowType = {
  WORLD_GEN: 'WORLD_GEN',
  CHARACTER_GEN: 'CHARACTER_GEN',
  KEY_CHARACTER_GEN: 'KEY_CHARACTER_GEN',
  STORY_OPENING: 'STORY_OPENING',
  NARRATION_I: 'NARRATION_I',
  NARRATION_II: 'NARRATION_II',
  HISTORY_SUMMARY: 'HISTORY_SUMMARY',
};

export const ChatRole = {
  PLAYER: 'player',
  KP: 'kp',
  SYSTEM: 'system',
  SUMMARY: 'summary',
};

export const ChatEntryType = {
  PROMPT: 'prompt',
  NARRATION: 'narration',
  RAW: 'raw',
  SUMMARY: 'summary',
  SYSTEM: 'system',
};

export const GameAction = {
  ENTER_WORLD_SETTING: 'ENTER_WORLD_SETTING',
  ENTER_CHARACTER_SETTING: 'ENTER_CHARACTER_SETTING',
  ENTER_KEY_CHARACTER_SETTING: 'ENTER_KEY_CHARACTER_SETTING',
  INVITE_NEXT_KEY_CHARACTER: 'INVITE_NEXT_KEY_CHARACTER',
  SAVE_KEY_CHARACTER: 'SAVE_KEY_CHARACTER',
  OPEN_STORY: 'OPEN_STORY',
  SEND_MESSAGE: 'SEND_MESSAGE',
  SAVE_WORLD: 'SAVE_WORLD',
  SAVE_CHARACTER: 'SAVE_CHARACTER',
  UPDATE_PROTAGONIST: 'UPDATE_PROTAGONIST',
};
